### ISSUE TITLE
build failed because some functions were not declared

### ISSUE THREAD

**Issue by masterAllen** [radareorg/r2ghidra-dec#80] opened 2020-02-13 07:12 UTC
I just used 'r2pm -i r2ghidra-dec' to install. Unfortunately, it failed with saying some functions were not decalred. Of course the pdg command don't work in radare2.

##### The list of functions that were not decalred
- r_anal_get_function_at
- r_anal_get_functions_in
- r_anal_function_contains

##### Environment
- OS: Arch Linux
- GCC Version: 9.2.0
- BISON: /usr/bin/bison (found version "3.5.1") 
- FLEX: /usr/bin/flex (found version "2.6.4") 
- PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 

##### Error Message
```
make[1]: Entering directory '/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/build'
make[2]: Entering directory '/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/build'
make[2]: Entering directory '/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/build'
make[2]: Entering directory '/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/build'
make[2]: Entering directory '/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/build'
...
...
make[2]: Leaving directory '/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/build'
make[2]: Entering directory '/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/build'
[ 42%] Building CXX object ghidra/CMakeFiles/sleighc.dir/ghidra/Ghidra/Features/Decompiler/src/decompile/cpp/slgh_compile.cc.o
/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/src/core_ghidra.cpp:530:18: warning: ‘radare_plugin’ initialized and declared ‘extern’
  530 | R_API RLibStruct radare_plugin = {
      |                  ^~~~~~~~~~~~~
[ 43%] Building CXX object CMakeFiles/core_ghidra.dir/src/R2Scope.cpp.o
[ 43%] Building CXX object CMakeFiles/core_ghidra.dir/src/R2TypeFactory.cpp.o
[ 44%] Building CXX object CMakeFiles/core_ghidra.dir/src/R2CommentDatabase.cpp.o
/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/src/R2Scope.cpp: In member function ‘Symbol* R2Scope::queryR2Absolute(long long unsigned int, bool) const’:
/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/src/R2Scope.cpp:436:23: error: ‘r_anal_get_function_at’ was not declared in this scope; did you mean ‘r_anal_get_fcn_at’?
  436 |  RAnalFunction *fcn = r_anal_get_function_at(core->anal, addr);
      |                       r_anal_get_fcn_at
[ 44%] Building CXX object ghidra/CMakeFiles/sleighc.dir/bison/slghparse.cpp.o
/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/src/R2CommentDatabase.cpp: In member function ‘void R2CommentDatabase::fillCache(const Address&) const’:
/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/src/R2CommentDatabase.cpp:20:23: error: ‘r_anal_get_function_at’ was not declared in this scope; did you mean ‘r_anal_get_fcn_at’?
   20 |  RAnalFunction *fcn = r_anal_get_function_at(core->anal, fad.getOffset());
      |                       ^~~~~~~~~~~~~~~~~~~~~~
      |                       r_anal_get_fcn_at
/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/src/R2CommentDatabase.cpp:23:17: error: ‘r_anal_get_functions_in’ was not declared in this scope; did you mean ‘r_anal_get_fcn_in’?
   23 |   RList *fcns = r_anal_get_functions_in(core->anal, fad.getOffset());
      |                 ^~~~~~~~~~~~~~~~~~~~~~~
      |                 r_anal_get_fcn_in
/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/src/R2CommentDatabase.cpp: In lambda function:
/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/src/R2CommentDatabase.cpp:36:7: error: ‘r_anal_function_contains’ was not declared in this scope; did you mean ‘r_anal_fcn_contains’?
   36 |   if(!r_anal_function_contains(fcn, item->from))
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
      |       r_anal_fcn_contains
make[2]: *** [CMakeFiles/core_ghidra.dir/build.make:102: CMakeFiles/core_ghidra.dir/src/R2Scope.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 45%] Building CXX object ghidra/CMakeFiles/sleighc.dir/flex/slghscan.cpp.o
make[2]: *** [CMakeFiles/core_ghidra.dir/build.make:128: CMakeFiles/core_ghidra.dir/src/R2CommentDatabase.cpp.o] Error 1
make[2]: Leaving directory '/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/build'
make[1]: *** [CMakeFiles/Makefile2:128: CMakeFiles/core_ghidra.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 46%] Linking CXX executable sleighc
make[2]: Leaving directory '/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/build'
[ 46%] Built target sleighc
make[1]: Leaving directory '/home/allen/.local/share/radare2/r2pm/git/r2ghidra-dec.git/build'
make: *** [Makefile:130: all] Error 2
```

**Comment by radare** [comment] 2020-02-13 07:29
And your version of r2 is...?

**Comment by thestr4ng3r** [comment] 2020-02-13 07:34
Duplicate of #76

**Closed by thestr4ng3r** 2020-02-13 07:34 UTC
Labels: duplicate
