### ISSUE TITLE
commenting in disassembly breaks decompilation

### ISSUE THREAD

**Issue by psifertex** [radareorg/r2ghidra-dec#34] opened 2019-09-09 01:48 UTC
**Environment information**
* Operating System: 10.14.6
* Cutter version: Version 1.9.0
Using r2-3.8.0
Based on Qt 5.12.1 (Clang 10.0 (Apple), 64 bit)

* File format: ELF, but doesn't look like an elf specific bug.

**Describe the bug**

Adding comments in disassembly (and maybe even to source I've just tested that less) frequently breaks decompilation, though exactly how it breaks appears inconsistent (maybe dependent on the comment content or length?)

**To Reproduce**

1. Open any file (In the screenshot I'm using  "bomb" from: http://csapp.cs.cmu.edu/3e/bomb.tar but I've tested other files with similar results) with default Cutter 1.9 settings 
2. Enable disassembly graph
3. Click on main
3. Start adding comments
4. Decompilation becomes corrupted

**Expected behavior**

Decompilation is not corrupted but rather shows comments in the appropriate location, or not at all. 

**Screenshots**

In this screenshot, the first comment actually adds a "bad opcode" to the decompilation but the second comment /really/ breaks the output. 

![cutter-ghidra-comments](https://user-images.githubusercontent.com/140215/64498362-2469b680-d282-11e9-834e-22dbc71dae11.gif)

**Comment by thestr4ng3r** [comment] 2019-09-09 14:21
I can reproduce this issue with the Cutter Release on macOS, but it seems to be already fixed by https://github.com/radareorg/r2ghidra-dec/commit/0a2cbda7641ec3fb6e6079e05e3bc47aff8b0113. I can reproduce it quite reliably before the commit, but not after it.

About the crash, I am quite sure it is the same issue too, but just to be sure it would be good if you could extract a stacktrace from it. To do so, clone `https://chromium.googlesource.com/breakpad/breakpad`, `./configure && make`, then run `src/processor/minidump_stackwalk ~/Cutter_crash_dump_<...>.dmp symbols` with symbols being the folder from here:
[cutter-v1.9.0-macos-symbols.tar.gz](https://github.com/radareorg/r2ghidra-dec/files/3590946/cutter-v1.9.0-macos-symbols.tar.gz)

**Comment by psifertex** [comment] 2019-09-11 12:40
Stack trace attached. 
[stacktrace.txt](https://github.com/radareorg/r2ghidra-dec/files/3600795/stacktrace.txt)

**Comment by thestr4ng3r** [comment] 2019-09-11 14:50
Ok, the stacktrace doesn't say too much, but it's most likely that it is the same issue. Thanks!

**Closed by thestr4ng3r** 2019-09-11 14:50 UTC
