### ISSUE TITLE
Possibility to provide type information to ghidra

### ISSUE THREAD

**Issue by maximevince** [radareorg/r2ghidra-dec#35] opened 2019-09-09 18:06 UTC
Is there a possibility to provide type information, such a C structs to ghidra, such that the decompiler output becomes more readable?
Essentially passing the information from "t" in r2, to ghidra-dec ?

**Comment by thestr4ng3r** [comment] 2019-09-09 18:12
Yes it already does that for structs and enums if you change the type of a variable (does not work on sp-based vars, but that is by design).
Is it not working for you?

**Comment by ITAYC0HEN** [comment] 2019-09-11 12:39
@maximevince, this feature already exists in r2ghidra. You can load your C types and struct and then apply it to instructions or variables in radare2. The plugin well then tell ghidra about these structures and the Decompiler code will be shown with the types applied.

I will close this issue for the meantime. If you have any other question we'd be happy to answer. If you want to see a step by step example - let us know. :)

**Closed by ITAYC0HEN** 2019-09-11 12:39 UTC
